name: Deploy to server
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'ref to deploy'
        required: true
        default: 'main'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.version }}
      - name: Creating SSH connection
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/id_rsa
          chmod 600 ~/id_rsa
          mkdir ~/.ssh
          ssh-keyscan ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
          ssh -i ~/id_rsa ubuntu@${{ secrets.SERVER_HOST }} 'echo Success!'
      - name: Uploading code to server
        run: |
          ssh -i ~/id_rsa ubuntu@${{ secrets.SERVER_HOST }} '
          rm -rf /home/ubuntu/github_deploy
          '
          scp -i ~/id_rsa -r $GITHUB_WORKSPACE ubuntu@${{ secrets.SERVER_HOST }}:/home/ubuntu/github_deploy
      - name: Building container
        run: |
          ssh -i ~/id_rsa ubuntu@${{ secrets.SERVER_HOST }} '
          export VERSION_SHA=$(git rev-parse --short HEAD) 
          cd /home/ubuntu/github_deploy && \
          docker build -t pewpewbot:${{ github.event.inputs.version }} .
          '
      - name: Removing old container
        run: |
          ssh -i ~/id_rsa ubuntu@${{ secrets.SERVER_HOST }} '
          docker rm -f pewpewbot_gh_action || true
          '
      - name: Starting container
        run: |
          ssh -i ~/id_rsa ubuntu@${{ secrets.SERVER_HOST }} '
          docker run 
          --name pewpewbot_gh_action
          -e API_TOKEN=${{ secrets.API_TOKEN }}
          -e LOGIN=${{ secrets.LOGIN }}
          -e PASSWORD=${{ secrets.PASSWORD }}
          -e VERSION=$VERSION_SHA
          -v logs:/logs
          -d
          pewpewbot:${{ github.event.inputs.version }}
          '
          