name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'ref to deploy'
        required: true
        default: 'main'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.version }}
      - name: Creating SSH connection
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/id_rsa
          chmod 600 ~/id_rsa
          mkdir ~/.ssh
          ssh-keyscan ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
          scp -i ~/id_rsa ubuntu@${{ secrets.SERVER_HOST }} $GITHUB_WORKSPACE /home/ubuntu/github_deploy
          